package constants

const (
	ErrorMysqlCanal          = "Invalid canal"
	ErrorGetPosition         = "Invalid position. Error: \"%s\""
	ErrorSliceCreation       = "InterfaceSlice() given a non-slice type"
	ErrorNoColumn            = "There is no column %s in %s.%s"
	ErrorDBConnect           = "Can't connect to \"%s\""
	ErrorSave                = "Can't %s model in \"%s\""
	ErrorExecQuery           = "Can't exec query. Type: \"%s\" error: \"%v\""
	ErrorNoModelFile         = "Model file \"%s\" not exists"
	ErrorNoQueryFile         = "Model file \"%s\" not exists"
	ErrorModelFileExists     = "Model file \"%s\" already exists"
	ErrorParserPosition      = "Catch error: \"%s\""
	ErrorGetMinPosition      = "Can't get min position. Error: \"%s\""
	ErrorSetPosition         = "Can't set position. Error: \"%s\""
	ErrorEmptyPosition       = "Can't get position. Use \"destroy-slave\" and \"build-slave\""
	ErrorUndefinedSlave      = "Can't get slave."
	ErrorCobraStarter        = "Catch cobra error: \"%s\""
	ErrorCachePluginError    = "Catch plugin error: \"%s\""
	ErrorTableStructure      = "Can't read structure of table %s. Error : \"%s\""
	ErrorFieldTypeConversion = "Can't convert field type %s"
	ErrorBuildModelConfig    = "Can't build model config. Error: \"%s\""
	ErrorDumpRead            = "Can't read dump. Error: \"%s\""
	ErrorParseLine           = "Can't parse line \"%s\". Error: \"%s\""
	ErrorSlaveBuilt          = "Slave table \"%s\" already built. Use \"destroy-slave %s\" before build"
	ErrorSlaveConnector      = "Undefined slave connector"
	ErrorLogParsing          = "Can't parse log event"
	ErrorQueryFileRead       = "Can't read query file. Error: \"%s\""
)
